"""initial schema

Revision ID: 151d7467f12d
Revises: 
Create Date: 2026-07-22 00:44:56.953767
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '151d7467f12d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cover_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_author'), 'works', ['author'], unique=False)
    op.create_index(op.f('ix_works_slug'), 'works', ['slug'], unique=True)
    op.create_index(op.f('ix_works_status'), 'works', ['status'], unique=False)
    op.create_index(op.f('ix_works_title'), 'works', ['title'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('parent_case_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_work_id'), 'cases', ['work_id'], unique=False)
    op.create_table('chapter_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('graph_payload', sa.JSON(), nullable=False),
    sa.Column('timeline_payload', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'chapter', name='uq_snapshot_work_chapter')
    )
    op.create_index(op.f('ix_chapter_snapshots_work_id'), 'chapter_snapshots', ['work_id'], unique=False)
    op.create_table('editions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('source_format', sa.String(length=20), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('is_public_reference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_fingerprint')
    )
    op.create_index(op.f('ix_editions_isbn'), 'editions', ['isbn'], unique=False)
    op.create_index(op.f('ix_editions_work_id'), 'editions', ['work_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('first_chapter', sa.Integer(), nullable=False),
    sa.Column('identity_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_canonical_name'), 'people', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_people_work_id'), 'people', ['work_id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('published_by', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'version', name='uq_publication_work_version')
    )
    op.create_index(op.f('ix_publications_work_id'), 'publications', ['work_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('edition_id', sa.String(length=36), nullable=False),
    sa.Column('track', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_edition_id'), 'analysis_jobs', ['edition_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_work_id'), 'analysis_jobs', ['work_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('edition_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_locator', sa.JSON(), nullable=False),
    sa.Column('text_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'number', name='uq_chapter_edition_number')
    )
    op.create_index(op.f('ix_chapters_edition_id'), 'chapters', ['edition_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('introduced_chapter', sa.Integer(), nullable=False),
    sa.Column('resolved_chapter', sa.Integer(), nullable=True),
    sa.Column('reasoning_steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_case_id'), 'claims', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_work_id'), 'claims', ['work_id'], unique=False)
    op.create_table('private_library_books',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=True),
    sa.Column('edition_id', sa.String(length=36), nullable=True),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('current_chapter', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('private_overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_private_library_books_user_id'), 'private_library_books', ['user_id'], unique=False)
    op.create_index(op.f('ix_private_library_books_work_id'), 'private_library_books', ['work_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('chapter_id', sa.String(length=36), nullable=True),
    sa.Column('first_chapter', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('citation', sa.JSON(), nullable=False),
    sa.Column('lifecycle', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_first_chapter'), 'evidence', ['first_chapter'], unique=False)
    op.create_index(op.f('ix_evidence_work_id'), 'evidence', ['work_id'], unique=False)
    op.create_table('mystery_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_claim_id', sa.String(length=36), nullable=True),
    sa.Column('reveal_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mystery_questions_case_id'), 'mystery_questions', ['case_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('effect', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id')
    )
    op.create_table('person_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('first_chapter', sa.Integer(), nullable=False),
    sa.Column('merge_reveal_chapter', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_aliases_name'), 'person_aliases', ['name'], unique=False)
    op.create_index(op.f('ix_person_aliases_person_id'), 'person_aliases', ['person_id'], unique=False)
    op.create_table('person_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_id', sa.String(length=36), nullable=False),
    sa.Column('source_person_id', sa.String(length=36), nullable=False),
    sa.Column('target_person_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_chapter', sa.Integer(), nullable=False),
    sa.Column('resolved_chapter', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_relations_first_chapter'), 'person_relations', ['first_chapter'], unique=False)
    op.create_index(op.f('ix_person_relations_kind'), 'person_relations', ['kind'], unique=False)
    op.create_index(op.f('ix_person_relations_source_person_id'), 'person_relations', ['source_person_id'], unique=False)
    op.create_index(op.f('ix_person_relations_target_person_id'), 'person_relations', ['target_person_id'], unique=False)
    op.create_index(op.f('ix_person_relations_work_id'), 'person_relations', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_relations_work_id'), table_name='person_relations')
    op.drop_index(op.f('ix_person_relations_target_person_id'), table_name='person_relations')
    op.drop_index(op.f('ix_person_relations_source_person_id'), table_name='person_relations')
    op.drop_index(op.f('ix_person_relations_kind'), table_name='person_relations')
    op.drop_index(op.f('ix_person_relations_first_chapter'), table_name='person_relations')
    op.drop_table('person_relations')
    op.drop_index(op.f('ix_person_aliases_person_id'), table_name='person_aliases')
    op.drop_index(op.f('ix_person_aliases_name'), table_name='person_aliases')
    op.drop_table('person_aliases')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_mystery_questions_case_id'), table_name='mystery_questions')
    op.drop_table('mystery_questions')
    op.drop_index(op.f('ix_evidence_work_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_first_chapter'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_private_library_books_work_id'), table_name='private_library_books')
    op.drop_index(op.f('ix_private_library_books_user_id'), table_name='private_library_books')
    op.drop_table('private_library_books')
    op.drop_index(op.f('ix_claims_work_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_case_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_chapters_edition_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_analysis_jobs_work_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_edition_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_publications_work_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_people_work_id'), table_name='people')
    op.drop_index(op.f('ix_people_canonical_name'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_editions_work_id'), table_name='editions')
    op.drop_index(op.f('ix_editions_isbn'), table_name='editions')
    op.drop_table('editions')
    op.drop_index(op.f('ix_chapter_snapshots_work_id'), table_name='chapter_snapshots')
    op.drop_table('chapter_snapshots')
    op.drop_index(op.f('ix_cases_work_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_works_title'), table_name='works')
    op.drop_index(op.f('ix_works_status'), table_name='works')
    op.drop_index(op.f('ix_works_slug'), table_name='works')
    op.drop_index(op.f('ix_works_author'), table_name='works')
    op.drop_table('works')
    # ### end Alembic commands ###

